/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.ExcessInventory;

import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Organization.DonationManagementOrganization;
import Business.Organization.ExcessInventoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShortageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ProcessShortageRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ShortageWorkRequest request;
    ExcessInventoryOrganization organization;
    NGOEnterprise enterprise;
    UserAccount acc;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessShortageRequestJPanel(JPanel userProcessContainer, ShortageWorkRequest request, ExcessInventoryOrganization organization, Enterprise enterprise, UserAccount acc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        this.enterprise = (NGOEnterprise) enterprise;
        this.acc = acc;
        initializeTextFields();
    }

    private void initializeTextFields(){
        categoryJTextField.setText(String.valueOf(request.getCategory()));
        reqQuanttJTextField.setText(String.valueOf(request.getRequestedQuantity()));
        foodCountJTextField.setText(String.valueOf(enterprise.getFoodCount()));
        clothingCountJTextField.setText(String.valueOf(enterprise.getClothingCount()));
        moneyCountJTextField.setText(String.valueOf(enterprise.getMoney()));
        miscCountJTextField.setText(String.valueOf(enterprise.getMiscCount()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        foodCountJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clothingCountJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        moneyCountJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        miscCountJTextField = new javax.swing.JTextField();
        donateJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        categoryJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        reqQuanttJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Food Count");

        foodCountJTextField.setEditable(false);
        foodCountJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCountJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Check Inventory Work Request");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Clothing Count");

        clothingCountJTextField.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Money Count");

        moneyCountJTextField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Miscellaneous Inventory Count");

        miscCountJTextField.setEditable(false);

        donateJButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        donateJButton.setText("Distrubute");
        donateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Requested Product");

        categoryJTextField.setEditable(false);
        categoryJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryJTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Requested Quantity");

        reqQuanttJTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(donateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(moneyCountJTextField)
                        .addComponent(miscCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clothingCountJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foodCountJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reqQuanttJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqQuanttJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothingCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(miscCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ExcessInventoryWorkAreaJPanel dwjp = (ExcessInventoryWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void foodCountJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCountJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodCountJTextFieldActionPerformed

    private int changeInventoryCount(int count, ShortageWorkRequest request){
        
        int requestedQuantity = request.getRequestedQuantity() - request.getDonatedQuantity();
        if(count - requestedQuantity >= 0){
            request.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Full Donation Made");
            request.setDonatedQuantity(requestedQuantity);
            List workRequestList = organization.getWorkQueue().getWorkRequestList();
            workRequestList.remove(request);
            return count - requestedQuantity;
        }
        else{
            request.setDonatedQuantity(count);
            JOptionPane.showMessageDialog(null, "Donated only " + count);
            request.setStatus("Partially Completed");
            return 0;
        }
    }
    
    
    private void donateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateJButtonActionPerformed
        // TODO add your handling code here:

        if(request.getCategory().getValue().equals("Food"))
            enterprise.setFoodCount(changeInventoryCount(enterprise.getFoodCount(), request));
        else if(request.getCategory().getValue().equals("Clothing"))
            enterprise.setClothingCount(changeInventoryCount(enterprise.getClothingCount(), request));
        else if(request.getCategory().getValue().equals("Money"))
            enterprise.setMoney(changeInventoryCount(enterprise.getMoney(), request));
        else if(request.getCategory().getValue().equals("Miscellaneous"))
            enterprise.setMiscCount(changeInventoryCount(enterprise.getMiscCount(), request));
        request.setResolveDate(new Date());
        initializeTextFields();
        
        JOptionPane.showMessageDialog(null, "Donated successfully");
        
        categoryJTextField.setText("");
        reqQuanttJTextField.setText("");
        foodCountJTextField.setText("");
        clothingCountJTextField.setText("");
        moneyCountJTextField.setText("");
        miscCountJTextField.setText("");
        
        
    }//GEN-LAST:event_donateJButtonActionPerformed

    private void categoryJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField categoryJTextField;
    private javax.swing.JTextField clothingCountJTextField;
    private javax.swing.JButton donateJButton;
    private javax.swing.JTextField foodCountJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField miscCountJTextField;
    private javax.swing.JTextField moneyCountJTextField;
    private javax.swing.JTextField reqQuanttJTextField;
    // End of variables declaration//GEN-END:variables
}
